"""schema iniziale

Revision ID: 8e1021f67739
Revises: 
Create Date: 2026-08-05 13:58:51.375513
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8e1021f67739'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('tipo', sa.Enum('transizione_stato', 'azione_manuale', 'comunicazione', 'pagamento', 'sincronizzazione', name='tipoevento', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('entita', sa.String(length=32), nullable=False),
    sa.Column('entita_id', sa.String(length=32), nullable=False),
    sa.Column('stato_precedente', sa.String(length=32), nullable=True),
    sa.Column('stato_successivo', sa.String(length=32), nullable=True),
    sa.Column('operatore', sa.String(length=64), nullable=True),
    sa.Column('dettaglio', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_audit_log_tenant_id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_entita', 'audit_log', ['tenant_id', 'entita', 'entita_id'], unique=False)
    op.create_table('mandante',
    sa.Column('ragione_sociale', sa.String(length=255), nullable=False),
    sa.Column('partita_iva', sa.String(length=20), nullable=False),
    sa.Column('pacchetto', sa.Enum('entry', 'value', 'premium', name='pacchetto', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('alias_email', sa.String(length=255), nullable=True),
    sa.Column('credit_manager_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_mandante_tenant_id'),
    sa.UniqueConstraint('tenant_id', name='uq_mandante_tenant')
    )
    op.create_index(op.f('ix_mandante_tenant_id'), 'mandante', ['tenant_id'], unique=False)
    op.create_table('cliente_finale',
    sa.Column('mandante_id', sa.String(length=32), nullable=False),
    sa.Column('denominazione', sa.String(length=255), nullable=False),
    sa.Column('piva_cf', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pec', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('canali_opt_out', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'mandante_id'], ['mandante.tenant_id', 'mandante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_cliente_finale_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'piva_cf', name='uq_cliente_tenant_piva')
    )
    op.create_index(op.f('ix_cliente_finale_mandante_id'), 'cliente_finale', ['mandante_id'], unique=False)
    op.create_index(op.f('ix_cliente_finale_tenant_id'), 'cliente_finale', ['tenant_id'], unique=False)
    op.create_table('flusso',
    sa.Column('mandante_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'mandante_id'], ['mandante.tenant_id', 'mandante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_flusso_tenant_id')
    )
    op.create_index(op.f('ix_flusso_mandante_id'), 'flusso', ['mandante_id'], unique=False)
    op.create_index(op.f('ix_flusso_tenant_id'), 'flusso', ['tenant_id'], unique=False)
    op.create_table('flusso_step',
    sa.Column('flusso_id', sa.String(length=32), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('offset_giorni', sa.Integer(), nullable=False),
    sa.Column('canale', sa.Enum('email', 'pec', 'whatsapp', 'voice', name='canale', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'flusso_id'], ['flusso.tenant_id', 'flusso.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'flusso_id', 'ordine', name='uq_step_flusso_ordine'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_flusso_step_tenant_id')
    )
    op.create_index(op.f('ix_flusso_step_flusso_id'), 'flusso_step', ['flusso_id'], unique=False)
    op.create_index(op.f('ix_flusso_step_tenant_id'), 'flusso_step', ['tenant_id'], unique=False)
    op.create_table('posizione',
    sa.Column('cliente_id', sa.String(length=32), nullable=False),
    sa.Column('stato', sa.Enum('aperta', 'chiusa', name='statoposizione', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'cliente_id'], ['cliente_finale.tenant_id', 'cliente_finale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', 'cliente_id', name='uq_posizione_cliente'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_posizione_tenant_id')
    )
    op.create_index(op.f('ix_posizione_cliente_id'), 'posizione', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_posizione_tenant_id'), 'posizione', ['tenant_id'], unique=False)
    op.create_table('fattura',
    sa.Column('posizione_id', sa.String(length=32), nullable=False),
    sa.Column('cliente_id', sa.String(length=32), nullable=False),
    sa.Column('numero', sa.String(length=64), nullable=False),
    sa.Column('data_emissione', sa.Date(), nullable=False),
    sa.Column('data_scadenza', sa.Date(), nullable=False),
    sa.Column('importo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('importo_residuo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stato', sa.Enum('gestione', 'pausa', 'saldata', 'insoluto', name='statofattura', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('pausa_fino_a', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('data_scadenza >= data_emissione', name='ck_fattura_scadenza_dopo_emissione'),
    sa.CheckConstraint('importo >= 0', name='ck_fattura_importo_non_negativo'),
    sa.CheckConstraint('importo_residuo <= importo', name='ck_fattura_residuo_entro_importo'),
    sa.CheckConstraint('importo_residuo >= 0', name='ck_fattura_residuo_non_negativo'),
    sa.ForeignKeyConstraint(['tenant_id', 'posizione_id', 'cliente_id'], ['posizione.tenant_id', 'posizione.id', 'posizione.cliente_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cliente_id', 'numero', name='uq_fattura_tenant_cliente_numero'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_fattura_tenant_id')
    )
    op.create_index(op.f('ix_fattura_cliente_id'), 'fattura', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_fattura_posizione_id'), 'fattura', ['posizione_id'], unique=False)
    op.create_index(op.f('ix_fattura_tenant_id'), 'fattura', ['tenant_id'], unique=False)
    op.create_index('ix_fattura_tenant_scadenza', 'fattura', ['tenant_id', 'data_scadenza'], unique=False)
    op.create_index('ix_fattura_tenant_stato', 'fattura', ['tenant_id', 'stato'], unique=False)
    op.create_table('comunicazione',
    sa.Column('fattura_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('canale', sa.Enum('email', 'pec', 'whatsapp', 'voice', name='canale', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=False),
    sa.Column('programmata_per', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inviata_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stato', sa.Enum('programmata', 'inviata', 'annullata', 'fallita', name='statocomunicazione', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('operatore', sa.String(length=64), nullable=True),
    sa.Column('esito_recapito', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'fattura_id'], ['fattura.tenant_id', 'fattura.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'step_id'], ['flusso_step.tenant_id', 'flusso_step.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fattura_id', 'step_id', name='uq_comunicazione_fattura_step'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_comunicazione_tenant_id')
    )
    op.create_index(op.f('ix_comunicazione_fattura_id'), 'comunicazione', ['fattura_id'], unique=False)
    op.create_index(op.f('ix_comunicazione_tenant_id'), 'comunicazione', ['tenant_id'], unique=False)
    op.create_index('ix_comunicazione_tenant_programmata', 'comunicazione', ['tenant_id', 'programmata_per'], unique=False)
    op.create_table('pagamento',
    sa.Column('fattura_id', sa.String(length=32), nullable=False),
    sa.Column('importo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('origine', sa.Enum('riconciliazione', 'manuale', name='originepagamento', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('chiave_idempotenza', sa.String(length=128), nullable=False),
    sa.Column('operatore', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'fattura_id'], ['fattura.tenant_id', 'fattura.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chiave_idempotenza', name='uq_pagamento_tenant_chiave'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_pagamento_tenant_id')
    )
    op.create_index(op.f('ix_pagamento_fattura_id'), 'pagamento', ['fattura_id'], unique=False)
    op.create_index(op.f('ix_pagamento_tenant_id'), 'pagamento', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamento_tenant_id'), table_name='pagamento')
    op.drop_index(op.f('ix_pagamento_fattura_id'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index('ix_comunicazione_tenant_programmata', table_name='comunicazione')
    op.drop_index(op.f('ix_comunicazione_tenant_id'), table_name='comunicazione')
    op.drop_index(op.f('ix_comunicazione_fattura_id'), table_name='comunicazione')
    op.drop_table('comunicazione')
    op.drop_index('ix_fattura_tenant_stato', table_name='fattura')
    op.drop_index('ix_fattura_tenant_scadenza', table_name='fattura')
    op.drop_index(op.f('ix_fattura_tenant_id'), table_name='fattura')
    op.drop_index(op.f('ix_fattura_posizione_id'), table_name='fattura')
    op.drop_index(op.f('ix_fattura_cliente_id'), table_name='fattura')
    op.drop_table('fattura')
    op.drop_index(op.f('ix_posizione_tenant_id'), table_name='posizione')
    op.drop_index(op.f('ix_posizione_cliente_id'), table_name='posizione')
    op.drop_table('posizione')
    op.drop_index(op.f('ix_flusso_step_tenant_id'), table_name='flusso_step')
    op.drop_index(op.f('ix_flusso_step_flusso_id'), table_name='flusso_step')
    op.drop_table('flusso_step')
    op.drop_index(op.f('ix_flusso_tenant_id'), table_name='flusso')
    op.drop_index(op.f('ix_flusso_mandante_id'), table_name='flusso')
    op.drop_table('flusso')
    op.drop_index(op.f('ix_cliente_finale_tenant_id'), table_name='cliente_finale')
    op.drop_index(op.f('ix_cliente_finale_mandante_id'), table_name='cliente_finale')
    op.drop_table('cliente_finale')
    op.drop_index(op.f('ix_mandante_tenant_id'), table_name='mandante')
    op.drop_table('mandante')
    op.drop_index('ix_audit_tenant_entita', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
